using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Cataphract : MonoBehaviour
{
	void Start ()
	{
        int EnergyMax = 8;
        int ShieldEnergyMax = 2;
        int EngineEnergyMax = 2;
        int OxygenEnergyMax = 1;
        int MedbayEnergyMax = 1;
        int WeaponEnergyMax = 4;
        int CockpitEnergyMax = 1;
        int DoorEnergyMax = 1;
        int SensorEnergyMax = 1;
        int CloakEnergyMax = 0;
        int Weapon1ID = 1;
        int Weapon2ID = 7;
        int Weapon3ID = 0;
        int Weapon4ID = 0;
        int Scrap = 1000;
        int Fuel = 1000;
        int Ammo = 3;
        bool Cloak = false;
		int HullHp = 30;

        gameObject.GetComponent<Ship>().InitializeStats(EnergyMax, ShieldEnergyMax, EngineEnergyMax, OxygenEnergyMax, MedbayEnergyMax, WeaponEnergyMax, CloakEnergyMax, CockpitEnergyMax, DoorEnergyMax, SensorEnergyMax, Weapon1ID, Weapon2ID, Weapon3ID, Weapon4ID, Scrap, Fuel, Ammo, Cloak, HullHp);
        //ShipWidth+3=18, ShipHeight+3=9
        gameObject.GetComponent<Ship> ().Initialize (18, 9);
		//x, y, orientation
		gameObject.GetComponent<Ship> ().InitializeWalls (8, 2, "left");
		gameObject.GetComponent<Ship> ().InitializeWalls (8, 2, "top");
		gameObject.GetComponent<Ship> ().InitializeWalls (8, 2, "bottom");
		gameObject.GetComponent<Ship> ().InitializeWalls (9, 2, "top");
		gameObject.GetComponent<Ship> ().InitializeWalls (9, 2, "right");
		gameObject.GetComponent<Ship> ().InitializeWalls (9, 2, "bottom");
		gameObject.GetComponent<Ship> ().InitializeWalls (3, 3, "left");
		gameObject.GetComponent<Ship> ().InitializeWalls (3, 3, "top");
		gameObject.GetComponent<Ship> ().InitializeWalls (3, 3, "bottom");
		gameObject.GetComponent<Ship> ().InitializeWalls (4, 3, "top");
		gameObject.GetComponent<Ship> ().InitializeWalls (4, 3, "right");
		gameObject.GetComponent<Ship> ().InitializeWalls (4, 3, "bottom");
		gameObject.GetComponent<Ship> ().InitializeWalls (5, 3, "left");
		gameObject.GetComponent<Ship> ().InitializeWalls (5, 3, "top");
		gameObject.GetComponent<Ship> ().InitializeWalls (5, 3, "bottom");
		gameObject.GetComponent<Ship> ().InitializeWalls (6, 3, "top");
		gameObject.GetComponent<Ship> ().InitializeWalls (6, 3, "right");
		gameObject.GetComponent<Ship> ().InitializeWalls (6, 3, "bottom");
		gameObject.GetComponent<Ship> ().InitializeWalls (8, 3, "left");
		gameObject.GetComponent<Ship> ().InitializeWalls (8, 3, "top");
		gameObject.GetComponent<Ship> ().InitializeWalls (9, 3, "top");
		gameObject.GetComponent<Ship> ().InitializeWalls (9, 3, "right");
		gameObject.GetComponent<Ship> ().InitializeWalls (10, 3, "left");
		gameObject.GetComponent<Ship> ().InitializeWalls (10, 3, "top");
		gameObject.GetComponent<Ship> ().InitializeWalls (11, 3, "top");
		gameObject.GetComponent<Ship> ().InitializeWalls (11, 3, "right");
		gameObject.GetComponent<Ship> ().InitializeWalls (2, 4, "left");
		gameObject.GetComponent<Ship> ().InitializeWalls (2, 4, "top");
		gameObject.GetComponent<Ship> ().InitializeWalls (2, 4, "right");
		gameObject.GetComponent<Ship> ().InitializeWalls (3, 4, "left");
		gameObject.GetComponent<Ship> ().InitializeWalls (3, 4, "top");
		gameObject.GetComponent<Ship> ().InitializeWalls (4, 4, "top");
		gameObject.GetComponent<Ship> ().InitializeWalls (4, 4, "right");
		gameObject.GetComponent<Ship> ().InitializeWalls (6, 4, "left");
		gameObject.GetComponent<Ship> ().InitializeWalls (6, 4, "top");
		gameObject.GetComponent<Ship> ().InitializeWalls (7, 4, "top");
		gameObject.GetComponent<Ship> ().InitializeWalls (7, 4, "right");
		gameObject.GetComponent<Ship> ().InitializeWalls (8, 4, "left");
		gameObject.GetComponent<Ship> ().InitializeWalls (8, 4, "bottom");
		gameObject.GetComponent<Ship> ().InitializeWalls (9, 4, "bottom");
		gameObject.GetComponent<Ship> ().InitializeWalls (9, 4, "right");
		gameObject.GetComponent<Ship> ().InitializeWalls (10, 4, "left");
		gameObject.GetComponent<Ship> ().InitializeWalls (10, 4, "bottom");
		gameObject.GetComponent<Ship> ().InitializeWalls (11, 4, "bottom");
		gameObject.GetComponent<Ship> ().InitializeWalls (11, 4, "right");
		gameObject.GetComponent<Ship> ().InitializeWalls (12, 4, "left");
		gameObject.GetComponent<Ship> ().InitializeWalls (12, 4, "top");
		gameObject.GetComponent<Ship> ().InitializeWalls (12, 4, "bottom");
		gameObject.GetComponent<Ship> ().InitializeWalls (13, 4, "top");
		gameObject.GetComponent<Ship> ().InitializeWalls (13, 4, "right");
		gameObject.GetComponent<Ship> ().InitializeWalls (13, 4, "bottom");
		gameObject.GetComponent<Ship> ().InitializeWalls (14, 4, "left");
		gameObject.GetComponent<Ship> ().InitializeWalls (14, 4, "top");
		gameObject.GetComponent<Ship> ().InitializeWalls (15, 4, "top");
		gameObject.GetComponent<Ship> ().InitializeWalls (15, 4, "right");
		gameObject.GetComponent<Ship> ().InitializeWalls (16, 4, "left");
		gameObject.GetComponent<Ship> ().InitializeWalls (16, 4, "top");
		gameObject.GetComponent<Ship> ().InitializeWalls (16, 4, "right");
		gameObject.GetComponent<Ship> ().InitializeWalls (2, 5, "left");
		gameObject.GetComponent<Ship> ().InitializeWalls (2, 5, "right");
		gameObject.GetComponent<Ship> ().InitializeWalls (2, 5, "bottom");
		gameObject.GetComponent<Ship> ().InitializeWalls (3, 5, "left");
		gameObject.GetComponent<Ship> ().InitializeWalls (3, 5, "bottom");
		gameObject.GetComponent<Ship> ().InitializeWalls (4, 5, "bottom");
		gameObject.GetComponent<Ship> ().InitializeWalls (4, 5, "right");
		gameObject.GetComponent<Ship> ().InitializeWalls (6, 5, "left");
		gameObject.GetComponent<Ship> ().InitializeWalls (6, 5, "bottom");
		gameObject.GetComponent<Ship> ().InitializeWalls (7, 5, "bottom");
		gameObject.GetComponent<Ship> ().InitializeWalls (7, 5, "right");
		gameObject.GetComponent<Ship> ().InitializeWalls (8, 5, "left");
		gameObject.GetComponent<Ship> ().InitializeWalls (8, 5, "top");
		gameObject.GetComponent<Ship> ().InitializeWalls (9, 5, "top");
		gameObject.GetComponent<Ship> ().InitializeWalls (9, 5, "right");
		gameObject.GetComponent<Ship> ().InitializeWalls (10, 5, "left");
		gameObject.GetComponent<Ship> ().InitializeWalls (10, 5, "top");
		gameObject.GetComponent<Ship> ().InitializeWalls (11, 5, "top");
		gameObject.GetComponent<Ship> ().InitializeWalls (11, 5, "right");
		gameObject.GetComponent<Ship> ().InitializeWalls (12, 5, "left");
		gameObject.GetComponent<Ship> ().InitializeWalls (12, 5, "top");
		gameObject.GetComponent<Ship> ().InitializeWalls (12, 5, "bottom");
		gameObject.GetComponent<Ship> ().InitializeWalls (13, 5, "top");
		gameObject.GetComponent<Ship> ().InitializeWalls (13, 5, "right");
		gameObject.GetComponent<Ship> ().InitializeWalls (13, 5, "bottom");
		gameObject.GetComponent<Ship> ().InitializeWalls (14, 5, "left");
		gameObject.GetComponent<Ship> ().InitializeWalls (14, 5, "bottom");
		gameObject.GetComponent<Ship> ().InitializeWalls (15, 5, "bottom");
		gameObject.GetComponent<Ship> ().InitializeWalls (15, 5, "right");
		gameObject.GetComponent<Ship> ().InitializeWalls (16, 5, "left");
		gameObject.GetComponent<Ship> ().InitializeWalls (16, 5, "right");
		gameObject.GetComponent<Ship> ().InitializeWalls (16, 5, "bottom");
		gameObject.GetComponent<Ship> ().InitializeWalls (3, 6, "left");
		gameObject.GetComponent<Ship> ().InitializeWalls (3, 6, "top");
		gameObject.GetComponent<Ship> ().InitializeWalls (3, 6, "bottom");
		gameObject.GetComponent<Ship> ().InitializeWalls (4, 6, "top");
		gameObject.GetComponent<Ship> ().InitializeWalls (4, 6, "right");
		gameObject.GetComponent<Ship> ().InitializeWalls (4, 6, "bottom");
		gameObject.GetComponent<Ship> ().InitializeWalls (5, 6, "left");
		gameObject.GetComponent<Ship> ().InitializeWalls (5, 6, "top");
		gameObject.GetComponent<Ship> ().InitializeWalls (5, 6, "bottom");
		gameObject.GetComponent<Ship> ().InitializeWalls (6, 6, "top");
		gameObject.GetComponent<Ship> ().InitializeWalls (6, 6, "right");
		gameObject.GetComponent<Ship> ().InitializeWalls (6, 6, "bottom");
		gameObject.GetComponent<Ship> ().InitializeWalls (8, 6, "left");
		gameObject.GetComponent<Ship> ().InitializeWalls (8, 6, "bottom");
		gameObject.GetComponent<Ship> ().InitializeWalls (9, 6, "bottom");
		gameObject.GetComponent<Ship> ().InitializeWalls (9, 6, "right");
		gameObject.GetComponent<Ship> ().InitializeWalls (10, 6, "left");
		gameObject.GetComponent<Ship> ().InitializeWalls (10, 6, "bottom");
		gameObject.GetComponent<Ship> ().InitializeWalls (11, 6, "bottom");
		gameObject.GetComponent<Ship> ().InitializeWalls (11, 6, "right");
		gameObject.GetComponent<Ship> ().InitializeWalls (8, 7, "left");
		gameObject.GetComponent<Ship> ().InitializeWalls (8, 7, "top");
		gameObject.GetComponent<Ship> ().InitializeWalls (8, 7, "bottom");
		gameObject.GetComponent<Ship> ().InitializeWalls (9, 7, "top");
		gameObject.GetComponent<Ship> ().InitializeWalls (9, 7, "right");
		gameObject.GetComponent<Ship> ().InitializeWalls (9, 7, "bottom");
		gameObject.GetComponent<Ship> ().InitializeDoors ();
	}
}
